// demo-vue/app/examples/BottomNavigationBar.vue
<template>
    <Page>
        <ActionBar :title="title">
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="onNavigationButtonTap"/>
        </ActionBar>
        <GridLayout rows="*, auto" backgroundColor="blue">
            <StackLayout class="page" backgroundColor="white" row="0">
                <!-- <ns-first-tab *ngSwitchDefault></ns-first-tab> -->
                <!-- <ns-third-tab *ngSwitchCase="2"></ns-third-tab> -->
            </StackLayout>
            <MDBottomNavigationBar
                row="1"
                activeColor="red" 
                @loaded="onbottomNavigationBarLoaded"
                @tabPressed="onBottomNavigationTabPressed"
                @tabSelected="onBottomNavigationTabSelected"
                @tabReselected="onBottomNavigationTabReselected"                
            >
                <MDBottomNavigationTab title="First" icon="res://ic_home" activeColor="green"/>
                <MDBottomNavigationTab title="Second" icon="res://ic_view_list" isSelectable="false" />
                <MDBottomNavigationTab title="Third" icon="res://ic_menu" inactiveColor="brown"/>
            </MDBottomNavigationBar>
        </GridLayout>
    </Page>
</template>

<script lang="ts">
import * as frameModule from '@nativescript/core/ui/frame';
import { BottomNavigationBar, TabPressedEventData, TabReselectedEventData, TabSelectedEventData } from 'nativescript-material-bottomnavigationbar';
import { EventData } from '@nativescript/core/ui/core/view';

import Vue from 'vue';

export const title = 'BottomNavigationBar sample';

export default Vue.extend({
    name: 'BottomNavigationBar',
    data() {
        return {
            title: title
        };
    },
    methods: {
        onNavigationButtonTap() {
            frameModule.Frame.topmost().goBack();
        },
        onbottomNavigationBarLoaded(args: EventData): void {
            const bottomNavigationBar = args.object as BottomNavigationBar;
            bottomNavigationBar.showBadge(1);
            bottomNavigationBar.showBadge(2, 4);
        },

        onBottomNavigationTabPressed(args: TabPressedEventData): void {
            alert('This tab has isSelectable: false, and should be used to perform actions');
            console.log(`pressed tab index:  ${args.index}`);
        },

        onBottomNavigationTabSelected(args: TabSelectedEventData): void {
            console.log(`old tab index:  ${args.oldIndex}`);
            console.log(`selected tab index:  ${args.newIndex}`);
        },

        onBottomNavigationTabReselected(args: TabReselectedEventData): void {
            alert('Tab Reselected');
            console.log(`reselected tab index:  ${args.index}`);
        }
    }
});
</script>

// demo-ng/src/app/examples/bottom-navigation-bar/bottom-navigation-bar.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import {
    BottomNavigationBar,
    TabPressedEventData,
    TabReselectedEventData,
    TabSelectedEventData,
} from 'nativescript-material-bottomnavigationbar';

@Component({
    selector: 'ns-bottom-navigation-bar',
    templateUrl: 'bottom-navigation-bar.component.html',
    styleUrls: ['./bottom-navigation-bar.component.scss'],
})
export class BottomNavigationBarComponent {
    @ViewChild('bottomNavigationBar', { read: ElementRef, static: false })
    private _bottomNavigationBar: ElementRef<BottomNavigationBar>;

    onbottomNavigationBarLoaded(): void {
        const bottomNavigationBar = this._bottomNavigationBar.nativeElement;
        bottomNavigationBar.showBadge(1);
        bottomNavigationBar.showBadge(2, 4);
    }

    onBottomNavigationTabPressed(args: TabPressedEventData): void {
        alert('This tab has isSelectable: false, and should be used to perform actions');
        console.log(`pressed tab index:  ${args.index}`);
    }

    onBottomNavigationTabSelected(args: TabSelectedEventData): void {
        console.log(`old tab index:  ${args.oldIndex}`);
        console.log(`selected tab index:  ${args.newIndex}`);
    }

    onBottomNavigationTabReselected(args: TabReselectedEventData): void {
        alert('Tab Reselected');
        console.log(`reselected tab index:  ${args.index}`);
    }
}

<GridLayout rows="*, auto">
    <StackLayout class="page" [ngSwitch]="bottomNavigationBar.selectedTabIndex" row="0">
        <ns-first-tab *ngSwitchDefault></ns-first-tab>
        <ns-third-tab *ngSwitchCase="2"></ns-third-tab>
    </StackLayout>

    <BottomNavigationBar
        #bottomNavigationBar
        row="1"
        class="custom-bottom-navigation-bar"
        (loaded)="onbottomNavigationBarLoaded($event)"
        (tabPressed)="onBottomNavigationTabPressed($event)"
        (tabSelected)="onBottomNavigationTabSelected($event)"
        (tabReselected)="onBottomNavigationTabReselected($event)"
    >
        <BottomNavigationTab title="First" icon="res://ic_home"></BottomNavigationTab>
        <BottomNavigationTab title="Second" icon="res://ic_view_list" [isSelectable]="false"></BottomNavigationTab>
        <BottomNavigationTab title="Third" icon="res://ic_menu"></BottomNavigationTab>
    </BottomNavigationBar>
</GridLayout>
