// demo-vue/app/examples/BottomNavigation.vue
<template>
    <Page>
        <ActionBar :title="title">
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="onNavigationButtonTap" />
        </ActionBar>
        
        <MDBottomNavigation selectedIndex="1">
            <!-- The bottom tab UI is created via MDTabStrip (the containier) and MDTabStripItem (for each tab)-->
            <MDTabStrip>
                <MDTabStripItem>
                    <Label text="Home"/>
                    <Image src="font://mdi-home" class="mdi"/>
                </MDTabStripItem>
                <MDTabStripItem class="special">
                    <Label text="Account"/>
                    <Image src="font://mdi-account" class="mdi"/>
                </MDTabStripItem>
                <MDTabStripItem class="special">
                    <Label text="Search"/>
                    <Image src="font://mdi-magnify" class="mdi"/>
                </MDTabStripItem>
            </MDTabStrip>

            <!-- The number of MDTabContentItem components should corespond to the number of MDTabStripItem components -->
            <MDTabContentItem>
                <Frame>
                        <Page>
                    <GridLayout backgroundColor="red" @loaded="onLoaded('red')" @tap="navigateToTabsSample">
                    <Label text="Home Page" class="h2 text-center"></Label>
                </GridLayout>
                    </Page>
                    </Frame>
            </MDTabContentItem>
            <MDTabContentItem>
                <GridLayout backgroundColor="green" @loaded="onLoaded('green')">
                    <Label text="Account Page" class="h2 text-center"></Label>
                </GridLayout>
            </MDTabContentItem>
            <MDTabContentItem>
                <GridLayout backgroundColor="yellow" @loaded="onLoaded('yellow')">
                    <Label text="Search Page" class="h2 text-center"></Label>
                </GridLayout>
            </MDTabContentItem>
        </MDBottomNavigation>
    </Page>
</template>

<script lang="ts">
import * as frameModule from '@nativescript/core/ui/frame';
import { EventData } from '@nativescript/core';
import Tabs from './Tabs.vue';

import Vue from 'vue';

export const title = 'BottomNavigation sample';

export default Vue.extend({
    name: 'BottomNavigation',
    data() {
        return {
            title: title
        };
    },
    methods: {
        onNavigationButtonTap() {
            frameModule.Frame.topmost().goBack();
        },
        onLoaded(name) {
            console.log('onTabLoaded', name)
        },
        navigateToTabsSample() {
                this.$navigateTo(Tabs);

        }
    }
});
</script>

<style>

MDTabs {
  /* color: gold; */
}

/* MDTabContentItem.special {
  color: green;
}

MDTabStrip {
  color: skyblue;
    selected-item-color: white;
    un-selected-item-color: blue;
    highlight-color: yellow;
    background-color: green;
}

MDTabStripItem.special {
  color: teal;
}

MDTabStripItem.nested {
  color: teal;
}

MDTabStripItem:highlighted {
    background-color: red;
  color: yellowgreen;
} */

</style>

// demo-react/src/components/BottomNavigation.tsx
import * as React from 'react';

export function BottomNavigation() {
    const [selectedIndex, setSelectedIndex] = React.useState(0);

    return (
        <bottomNavigation
            selectedIndex={selectedIndex}
            onSelectedIndexChanged={(args) => {
                setSelectedIndex(args.newIndex);
            }}
            style={{ backgroundColor: 'orange' }}
        >
            {/* The bottomTab UI is created via tabStrip (the container) and tabStripItem (for each tab) */}
            <tabStrip nodeRole="tabStrip" style={{ backgroundColor: 'red' }}>
                <tabStripItem nodeRole="items">
                    <label nodeRole="label">Home</label>
                    <image nodeRole="image" src="font://&#xf015;" className="fas" />
                </tabStripItem>
                <tabStripItem nodeRole="items">
                    <label nodeRole="label">Account</label>
                    <image nodeRole="image" src="font://&#xf007;" className="fas" />
                </tabStripItem>
                <tabStripItem nodeRole="items">
                    <label nodeRole="label">Search</label>
                    <image nodeRole="image" src="font://&#xf00e;" className="fas" />
                </tabStripItem>
            </tabStrip>

            {/* The number of tabContentItem components should corespond to the number of TabStripItem components */}
            <tabContentItem nodeRole="items">
                <gridLayout style={{ backgroundColor: 'blue' }}>
                    <label style={{ color: 'white' }}>Home Page</label>
                </gridLayout>
            </tabContentItem>
            <tabContentItem nodeRole="items">
                <gridLayout style={{ backgroundColor: 'cyan' }}>
                    <label style={{ color: 'black' }}>Account Page</label>
                </gridLayout>
            </tabContentItem>
            <tabContentItem nodeRole="items">
                <gridLayout style={{ backgroundColor: 'magenta' }}>
                    <label style={{ color: 'black' }}>Search Page</label>
                </gridLayout>
            </tabContentItem>
        </bottomNavigation>
    );
}
