// demo-react/src/components/Tabs.tsx
import * as React from 'react';

export function Tabs() {
    const [selectedIndex, setSelectedIndex] = React.useState(0);

    return (
        <tabs
            selectedIndex={selectedIndex}
            onSelectedIndexChanged={(args) => {
                setSelectedIndex(args.newIndex);
            }}
            style={{ backgroundColor: 'orange' }}
        >
            {/* The bottomTab UI is created via tabStrip (the container) and tabStripItem (for each tab) */}
            <tabStrip nodeRole="tabStrip" style={{ backgroundColor: 'red' }}>
                <tabStripItem nodeRole="items">
                    <label nodeRole="label">Home</label>
                    <image nodeRole="image" src="font://&#xf015;" className="fas" />
                </tabStripItem>
                <tabStripItem nodeRole="items">
                    <label nodeRole="label">Account</label>
                    <image nodeRole="image" src="font://&#xf007;" className="fas" />
                </tabStripItem>
                <tabStripItem nodeRole="items">
                    <label nodeRole="label">Search</label>
                    <image nodeRole="image" src="font://&#xf00e;" className="fas" />
                </tabStripItem>
            </tabStrip>

            {/* The number of tabContentItem components should corespond to the number of TabStripItem components */}
            <tabContentItem nodeRole="items">
                <gridLayout style={{ backgroundColor: 'blue' }}>
                    <label style={{ color: 'white' }}>Home Page</label>
                </gridLayout>
            </tabContentItem>
            <tabContentItem nodeRole="items">
                <gridLayout style={{ backgroundColor: 'cyan' }}>
                    <label style={{ color: 'black' }}>Account Page</label>
                </gridLayout>
            </tabContentItem>
            <tabContentItem nodeRole="items">
                <gridLayout style={{ backgroundColor: 'magenta' }}>
                    <label style={{ color: 'black' }}>Search Page</label>
                </gridLayout>
            </tabContentItem>
        </tabs>
    );
}

// demo-ng/src/app/examples/tabs/tabs.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'ns-buttons',
    templateUrl: './tabs.component.html',
    moduleId: module.id
})
export class TabsComponent implements OnInit {
    ngOnInit() { }
}

<MDTabs selectedIndex="1">
  <!-- The bottom tab UI is created via TabStrip (the containier) and TabStripItem (for each tab)-->
  <TabStrip>
    <TabStripItem>
      <Label text="Home"></Label>
      <Image src="res://ic_home"></Image>
    </TabStripItem>
    <TabStripItem>
      <Label text="Account"></Label>
      <Image src="res://ic_view_list"></Image>
    </TabStripItem>
    <TabStripItem>
      <Label text="Search"></Label>
      <Image src="res://ic_menu"></Image>
    </TabStripItem>
  </TabStrip>

  <!-- The number of TabContentItem components should corespond to the number of TabStripItem components -->
  <TabContentItem>
    <GridLayout>
      <Label text="Home Page" class="h2 text-center"></Label>
    </GridLayout>
  </TabContentItem>
  <TabContentItem>
    <GridLayout>
      <Label text="Account Page" class="h2 text-center"></Label>
    </GridLayout>
  </TabContentItem>
  <TabContentItem>
    <GridLayout>
      <Label text="Search Page" class="h2 text-center"></Label>
    </GridLayout>
  </TabContentItem>
</MDTabs>
