// demo-ng/src/app/examples/tabs/tabs.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'ns-buttons',
    templateUrl: './tabs.component.html',
    moduleId: module.id
})
export class TabsComponent implements OnInit {
    ngOnInit() { }
}

<MDTabs selectedIndex="1">
  <!-- The bottom tab UI is created via TabStrip (the containier) and TabStripItem (for each tab)-->
  <TabStrip>
    <TabStripItem>
      <Label text="Home"></Label>
      <Image src="res://ic_home"></Image>
    </TabStripItem>
    <TabStripItem>
      <Label text="Account"></Label>
      <Image src="res://ic_view_list"></Image>
    </TabStripItem>
    <TabStripItem>
      <Label text="Search"></Label>
      <Image src="res://ic_menu"></Image>
    </TabStripItem>
  </TabStrip>

  <!-- The number of TabContentItem components should corespond to the number of TabStripItem components -->
  <TabContentItem>
    <GridLayout>
      <Label text="Home Page" class="h2 text-center"></Label>
    </GridLayout>
  </TabContentItem>
  <TabContentItem>
    <GridLayout>
      <Label text="Account Page" class="h2 text-center"></Label>
    </GridLayout>
  </TabContentItem>
  <TabContentItem>
    <GridLayout>
      <Label text="Search Page" class="h2 text-center"></Label>
    </GridLayout>
  </TabContentItem>
</MDTabs>

// demo-vue/app/examples/Tabs.vue
<template>
    <Page>
        <ActionBar :title="title">
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="onNavigationButtonTap" />
        </ActionBar>
        <MDTabs selectedIndex="1">
            <!-- The bottom tab UI is created via TabStrip (the containier) and TabStripItem (for each tab)-->
            <TabStrip>
                <TabStripItem>
                    <Label text="Home"></Label>
                    <Image src="font://󰋜" class="mdi"></Image>
                </TabStripItem>
                <TabStripItem class="special">
                    <Label text="Account"></Label>
                    <Image src="font://󰀄" class="mdi"></Image>
                </TabStripItem>
                <TabStripItem class="special">
                    <Label text="Search"></Label>
                    <Image src="font://󰜏" class="mdi"></Image>
                </TabStripItem>
            </TabStrip>

            <!-- The number of TabContentItem components should corespond to the number of TabStripItem components -->
            <TabContentItem>
                <GridLayout>
                    <Label text="Home Page" class="h2 text-center"></Label>
                </GridLayout>
            </TabContentItem>
            <TabContentItem>
                <GridLayout>
                    <Label text="Account Page" class="h2 text-center"></Label>
                </GridLayout>
            </TabContentItem>
            <TabContentItem>
                <GridLayout>
                    <Label text="Search Page" class="h2 text-center"></Label>
                </GridLayout>
            </TabContentItem>
        </MDTabs>
    </Page>
</template>

<script lang="ts">
import * as frameModule from '@nativescript/core/ui/frame';
import { Tabs } from 'nativescript-material-tabs';
import { EventData } from '@nativescript/core/ui/core/view';

import Vue from 'vue';

export const title = 'Tabs sample';

export default Vue.extend({
    name: 'Tabs',
    data() {
        return {
            title: title
        };
    },
    methods: {
        onNavigationButtonTap() {
            frameModule.topmost().goBack();
        }
    }
});
</script>

<style>
MDTabs.bottom-nav {
    background-color: orangered;
    color: gold;
    font-size: 18;
}

TabStripItem.tabstripitem-active {
    background-color: teal;
}

TabStripItem.tabstripitem-active:active {
    background-color: yellowgreen;
}

TabContentItem.first-tabcontent {
    background-color: seashell;
    color: olive;
}
TabContentItem.second-tabcontent {
    background-color: slategray;
    color: aquamarine;
}
TabContentItem.third-tabcontent {
    background-color: blueviolet;
    color: antiquewhite;
}
MDTabs TabStrip {
    highlight-color: red;
}
</style>
