// dev_demo/app/textfields/textfields.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    moduleId: module.id,
	selector: 'textfields',
	templateUrl: 'textfields.component.html'
})

export class TextfieldsComponent implements OnInit {
	textField
	constructor() { }

	ngOnInit() { }
	onFocus(command, e) {
        console.log('onFocus', command);
    }
    onBlur(command, e) {
        console.log('onBlur', command);
    }
    returnPress(command, e) {
        console.log('returnPress', command);
        // e.object.blur();
    }
    onTextChange(command, e) {
        console.log('onTextChange', command);
    }
}
<MaterialCard margin="20" rippleColor="green" borderRadius="10">
    <StackLayout horizontalAlignment="center">
        <MaterialTextField #textField1 helper="help me!" width="250" backgroundColor="orange" placeholderColor="green" keyboardType="datetime"
            hint="i am an hint" returnKeyType="next" (focus)="onFocus('textfield1',$event)" (blur)="onBlur('textfield1',$event)"
            (textChange)="onTextChange('textfield1',$event)"></MaterialTextField>
        <MaterialTextField #textField2 maxLength="10" hint="hint me" (returnPress)="returnPress(textField2.text,$event)"></MaterialTextField>
        <MaterialTextField #textField3 variant="outline" hint="outline"></MaterialTextField>
        <MaterialTextField  variant="filled" required email hint="fill this out..." [(ngModel)]="textField" #element #elementModel="ngModel" [error]="
        elementModel.errors? (elementModel.errors['email'] ?'invalid mail' : (elementModel.errors['required'] ?'required' : null)):null"></MaterialTextField>
    </StackLayout>
    
</MaterialCard>

// demo-vue/app/examples/TextFields.vue
<template>
    <Page>
        <ActionBar :title="title">
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="onNavigationButtonTap"></NavigationButton>
        </ActionBar>
        <StackLayout>
            <MDTextField id="textField1" helper="help me!" width="250" placeholderColor="green" keyboardType="datetime" hint="i am an hint" returnKeyType="next" v-model="value" highlightColor="yellow" @focus="onFocus" @blur="onBlur" @textChange="onTextChange" @returnPress="onReturnPress" />
            <StackLayout backgroundColor="red">
                <MDTextField id="textField2" hint="hint me" v-model="value" backgroundColor="green" @focus="onFocus" @blur="onBlur" @textChange="onTextChange" @returnPress="onReturnPress"  floating="false" margin="0" padding="20"/>
            </StackLayout>
            <MDTextField id="textField3"  maxLength="10" variant="outline" hint="outline" @focus="onFocus" @blur="onBlur" @textChange="onTextChange" @returnPress="onReturnPress" floatingColor="red" highlightColor="green" padding="10"/>
            <MDTextField id="textField4"  maxLength="10" variant="outline" hint="outline" @focus="onFocus" @blur="onBlur" @textChange="onTextChange" @returnPress="onReturnPress" floatingColor="red" placeholderColor="blue" highlightColor="green" padding="10"/>
            <MDTextField variant="filled" required="true" email="true" hint="fill this out..." @focus="onFocus" @blur="onBlur" floating="false" @textChange="onTextChange" @returnPress="onReturnPress"  highlightColor="red" padding="10"/>
        </StackLayout>
    </Page>
</template>

<script lang="ts">
import * as frameModule from 'tns-core-modules/ui/frame';
import Vue from 'vue';

export const title = 'Text fields sample';

export default Vue.extend({
    name: 'TextFields',

    data() {
        return {
            title: title,
            value: ''
        };
    },

    methods: {
        onNavigationButtonTap() {
            frameModule.topmost().goBack();
        },
        onFocus() {
            console.log('Focused');
        },
        onBlur() {
            console.log('Blurred');
        },
        onTextChange({ value }) {
            console.log(`Text changed to ${value}`);
        },
        onReturnPress() {
            console.log('Return key pressed');
        }
    }
});
</script>
