// demo-vue/app/examples/Buttons.vue
<template>
    <Page>
        <ActionBar :title="title">
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="onNavigationButtonTap"></NavigationButton>
        </ActionBar>
        <ScrollView>
            <StackLayout>
                <StackLayout margin="10">
                    <MDFloatingActionButton id="fab" src="res://ic_action_add" backgroundColor="blue" @tap="onTap" />
                </StackLayout>
                <StackLayout margin="10">
                    <MDButton id="button0" text="default button" @tap="onTap" />
                </StackLayout>
                <MDButton id="button1" elevation="5" borderRadius="10" fontSize="20" text="raised button" @tap="onTap" />
                <MDButton id="button2" class="bg-red" borderRadius="10" color="red" text="text button" variant="text" @tap="onTap">
                    <FormattedString>
                        <Span text="Words " color="#00ff00"></Span>
                        <Span text="with " color="#ff0000" fontAttributes="Bold"></Span>
                    </FormattedString>
                </MDButton>
                <MDButton id="button3" text="flat button \n test" variant="flat" class="bg-blue" @tap="onTap" />
                <MDButton id="button4" text="flat disabled button" isEnabled="false" backgroundColor="yellow" @tap="onTap" />
                <MDButton id="button5" text="outline button" color="black" width="200" variant="outline" @tap="onTap" />
                <MDButton id="button6" text="disabled outline button" isEnabled="false" width="200" variant="outline" @tap="onTap" />
                <MDButton id="button7" text="text button" width="200" color="blue" variant="text" @tap="onTap" />
                <MDButton id="button8" text="disabled text button" isEnabled="false" width="200" variant="text" @tap="onTap" />
                <MDButton id="button9" class="falseFAb bg-green" text="+" color="white" verticalAlign="center" backgroundColor="#53ba82" @tap="onTap" />
            </StackLayout>
        </ScrollView>
    </Page>
</template>

<script lang="ts">
import * as frameModule from 'tns-core-modules/ui/frame';
import Vue from 'vue';

export const title = 'Buttons sample';

export default Vue.extend({
    data() {
        return {
            name: 'Buttons',
            title: title
        };
    },
    methods: {
        onNavigationButtonTap() {
            frameModule.topmost().goBack();
        },
        onTap() {
            console.log('Button tapped');
        }
    }
});
</script>

// demo_ng/src/app/buttons/buttons.component.ts
import { Component, OnInit } from '@angular/core';
import { alert, prompt } from 'nativescript-material-dialogs';
import { Color } from 'tns-core-modules/color/color';

@Component({
    moduleId: module.id,
	selector: 'buttons',
	templateUrl: 'buttons.component.html'
})

export class ButtonsComponent implements OnInit {

	constructor() { }

	ngOnInit() { }
	onTap(command, e) {
        console.log('onTap', command);
		prompt({
			title:'alert test',
			message:command,
			okButtonText:'ok',
			// buttonTitleColor:new Color('blue'),
			// buttonInkColor:new Color('red')
	});
    }
}
<GridLayout rows="*" columns="*">
    <MDCardView margin="20" rippleColor="green" borderRadius="10">
        <StackLayout horizontalAlignment="center">
            <MDFloatingActionButton src="res://ic_action_add" backgroundColor="blue" (tap)="onTap('fab', $event)">
            </MDFloatingActionButton>
            <MDButton elevation="5" borderRadius="10" fontSize="20" text="raised button" (tap)="onTap('mbutton1', $event)"></MDButton>
            <MDButton borderRadius="10" color="red" text="text button" rippleColor="green" backgroundColor="red" variant="text" (tap)="onTap('mbutton2', $event)">
                <FormattedString>
                    <Span text="Words " color="#006600"></Span>
                    <Span text="with " color="#990000" fontAttributes="Bold"></Span>
                </FormattedString>
            </MDButton>
            <MDButton text="flat button \n test" rippleColor="red" backgroundColor="yellow" variant="flat" (tap)="onTap('mbutton3', $event)"></MDButton>
            <MDButton text="flat disabled button" isEnabled="false" rippleColor="red" backgroundColor="yellow" (tap)="onTap('mbutton3', $event)"></MDButton>
            <MDButton text="outline button" color="black" width="200" className="buttonYellow" variant="outline" (tap)="onTap('mbutton4', $event)"></MDButton>
            <MDButton text="disabled outline button" isEnabled="false" width="200" backgroundColor="yellow" variant="outline" (tap)="onTap('mbutton4', $event)"></MDButton>
            <MDButton text="text button" width="200" color="blue" variant="text" (tap)="onTap('mbutton4', $event)"></MDButton>
            <MDButton text="disabled text button" isEnabled="false" width="200" backgroundColor="yellow" variant="text" (tap)="onTap('mbutton4', $event)"></MDButton>
            <MDButton className="falseFAb" text="+" color="white" verticalAlign="center" backgroundColor="green" (tap)="onTap('mbutton5', $event)"></MDButton>
        </StackLayout>
    </MDCardView>
    
</GridLayout>
