// demo-snippets/ng/bottom-navigation-bar/bottom-navigation-bar.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { BottomNavigationBar, TabPressedEventData, TabReselectedEventData, TabSelectedEventData } from '@nativescript-community/ui-material-bottomnavigationbar';

@Component({
    moduleId: module.id,
    selector: 'ns-bottom-navigation-bar',
    templateUrl: './bottom-navigation-bar.component.html'
})
export class BottomNavigationBarComponent {
    @ViewChild('bottomNavigationBar', { read: ElementRef, static: false })
    private _bottomNavigationBar: ElementRef<BottomNavigationBar>;

    onbottomNavigationBarLoaded(): void {
        const bottomNavigationBar = this._bottomNavigationBar.nativeElement;
        bottomNavigationBar.showBadge(1);
        bottomNavigationBar.showBadge(2, 4);
    }

    onBottomNavigationTabPressed(args: TabPressedEventData): void {
        alert('This tab has isSelectable: false, and should be used to perform actions');
        console.log(`pressed tab index:  ${args.index}`);
    }

    onBottomNavigationTabSelected(args: TabSelectedEventData): void {
        console.log(`old tab index:  ${args.oldIndex}`);
        console.log(`selected tab index:  ${args.newIndex}`);
    }

    onBottomNavigationTabReselected(args: TabReselectedEventData): void {
        alert('Tab Reselected');
        console.log(`reselected tab index:  ${args.index}`);
    }
}

<ActionBar title="Demo" class="action-bar"></ActionBar>
<GridLayout rows="*, auto">
  <StackLayout
    class="page"
    [ngSwitch]="bottomNavigationBar.selectedTabIndex"
    row="0"
  >
    <ns-first-tab *ngSwitchDefault></ns-first-tab>
    <ns-third-tab *ngSwitchCase="2"></ns-third-tab>
  </StackLayout>

  <BottomNavigationBar
    #bottomNavigationBar
    row="1"
    class="custom-bottom-navigation-bar"
    (loaded)="onbottomNavigationBarLoaded()"
    (tabPressed)="onBottomNavigationTabPressed($event)"
    (tabSelected)="onBottomNavigationTabSelected($event)"
    (tabReselected)="onBottomNavigationTabReselected($event)"
  >
    <BottomNavigationTab
      title="First"
      icon="res://ic_home"
	  src="font://&#xF2Dc;" class="mdi"
    ></BottomNavigationTab>
    <BottomNavigationTab
      title="Second"
      icon="res://ic_view_list"
      [isSelectable]="false"
    ></BottomNavigationTab>
    <BottomNavigationTab
      title="Third"
      icon="res://ic_menu"
    ></BottomNavigationTab>
  </BottomNavigationBar>
</GridLayout>

// demo-snippets/vue/BottomNavigationBar.vue
<template>
    <Page>
        <ActionBar :title="title">
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="onNavigationButtonTap" />
        </ActionBar>
        <GridLayout class="page" backgroundColor="white" rows="*, auto">
            <MDTabs row="0" :selectedIndex="currentTab" swipeEnabled="false">
                <MDTabContentItem>
                    <GridLayout class="p-20">
                        <Label class="h1 text-center" text="First tab" textWrap="true"></Label>
                        <Button text="select sthird" @tap="selectThird" horizontalAlignment="center" verticalAlignment="bottom" />
                    </GridLayout>
                </MDTabContentItem>
                <MDTabContentItem>
                    <GridLayout class="p-20">
                        <Label class="h1 text-center" text="Third tab" textWrap="true"></Label>
                    </GridLayout>
                </MDTabContentItem>
            </MDTabs>
            <MDBottomNavigationBar
                ref="bottomBar"
                row="1"
                activeColor="blue"
                inactiveColor="green"
                selectedTabIndex="2"
                class="mdi"
                @loaded="onbottomNavigationBarLoaded"
                @tabPressed="onBottomNavigationTabPressed"
                @tabSelected="onBottomNavigationTabSelected"
                @tabReselected="onBottomNavigationTabReselected"
            >
                <MDBottomNavigationTab title="First" activeColor="green" class="mdi" />
                <MDBottomNavigationTab title="Second" icon="font://mdi-account" class="mdi" />
                <MDBottomNavigationTab title="Third" icon="res://ic_menu" inactiveColor="brown" isSelectable="false" />
            </MDBottomNavigationBar>
        </GridLayout>
    </Page>
</template>

<script lang="ts">
import * as frameModule from '@nativescript/core/ui/frame';
import { BottomNavigationBar, TabPressedEventData, TabReselectedEventData, TabSelectedEventData } from '@nativescript-community/ui-material-bottomnavigationbar';
import { EventData } from '@nativescript/core';

import Vue from 'vue';

export const title = 'BottomNavigationBar sample';

export default Vue.extend({
    name: 'BottomNavigationBar',
    data() {
        return {
            title,
            currentTab: 0
        };
    },
    methods: {
        selectThird() {
            this.$refs.bottomBar.nativeView.selectTab(2);
        },
        onNavigationButtonTap() {
            frameModule.Frame.topmost().goBack();
        },
        onbottomNavigationBarLoaded(args: EventData): void {
            const bottomNavigationBar = args.object as BottomNavigationBar;
            bottomNavigationBar.showBadge(1);
            bottomNavigationBar.showBadge(2, 4);
        },

        onBottomNavigationTabPressed(args: TabPressedEventData): void {
            alert('This tab has isSelectable: false, and should be used to perform actions');
            console.log(`pressed tab index:  ${args.index}`);
        },

        onBottomNavigationTabSelected(args: TabSelectedEventData): void {
            console.log(`old tab index:  ${args.oldIndex}`);
            console.log(`selected tab index:  ${args.newIndex}`);
            this.currentTab = args.newIndex;
        },

        onBottomNavigationTabReselected(args: TabReselectedEventData): void {
            alert('Tab Reselected');
            console.log(`reselected tab index:  ${args.index}`);
        }
    }
});
</script>
